version: '2'

services:
  node:
    image: isomorphic-K2R
    container_name: isomorphic-K2R
    build:
      context: .
    hostname: isomorphic-K2R
    restart: always
    ports:
      - "127.0.0.1:4001:4001"
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "5"
